### ISSUE TITLE
ftp transfer file prompt error

### ISSUE THREAD

**Issue by currencyporter** [TeamAmaze/AmazeFileManager#2064] opened 2020-10-29 05:51 UTC
**Describe the bug**
ftp transfer file prompt error,
**To Reproduce**
1. Go to 'If I copy the file named "道德經釋義_呂喦撰(掃葉山房重鐫本).djvu", I will get an error, but if I change the file name to English, I will succeed'
4. See error: An error occurred copying files to the FTP server. Check to see if you have permission to put files on this server
200 command TYPE okay;
227Entering Passive Mode(192.168.137.124.230.217);
501Invalid character in command

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 2]
 - OS: [e.g. Android 9]
 - Rooted: [e.g. No]
 - Version: [e.g. 3.3.4]
3.5.0
**Additional context**

**Comment by TranceLove** [comment] 2020-10-29 23:53
Problem can be reproduced using Windows 8.1 built-in FTP client.

Exception in logcat (Was overwriting the existing file, hence the `DELE` command, not an error)

```
2020-10-30 07:49:45.721 12384-14352/com.amaze.filemanager.debug W/FtpLoggingFilter: EXCEPTION :
    org.apache.mina.filter.codec.ProtocolDecoderException: java.nio.charset.MalformedInputException: Input length = 1 (Hexdump: 53 54 4F 52 20 E9 81 93 E5 BE B7 E7 B6 93 E9 87 8B E7 BE A9 5F E5 91 82 E5 96 A6 E6 92 B0 28 E6 8E 81 45 91 89 E5 B1 B1 E6 88 BF E9 87 8D E9 90 AB E6 9C AC 29 2E 64 6A 76 75 0D 0A)
        at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:240)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:947)
        at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74)
        at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:770)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:762)
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:704)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:812)
        at org.apache.mina.filter.codec.textline.TextLineDecoder.decodeAuto(TextLineDecoder.java:292)
        at org.apache.mina.filter.codec.textline.TextLineDecoder.decode(TextLineDecoder.java:198)
        at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:231)
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) 
        at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) 
        at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:947) 
        at org.apache.mina.core.filterchain.IoFilterEvent.fire(IoFilterEvent.java:74) 
        at org.apache.mina.core.session.IoEvent.run(IoEvent.java:63) 
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTask(OrderedThreadPoolExecutor.java:770) 
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.runTasks(OrderedThreadPoolExecutor.java:762) 
        at org.apache.mina.filter.executor.OrderedThreadPoolExecutor$Worker.run(OrderedThreadPoolExecutor.java:704) 
        at java.lang.Thread.run(Thread.java:764) 
2020-10-30 07:49:45.722 12384-14352/com.amaze.filemanager.debug W/DefaultFtpHandler: Client sent command that could not be decoded: 53 54 4F 52 20 E9 81 93 E5 BE B7 E7 B6 93 E9 87 8B E7 BE A9 5F E5 91 82 E5 96 A6 E6 92 B0 28 E6 8E 81 45 91 89 E5 B1 B1 E6 88 BF E9 87 8D E9 90 AB E6 9C AC 29 2E 64 6A 76 75 0D 0A
2020-10-30 07:49:45.726 12384-14351/com.amaze.filemanager.debug I/FtpLoggingFilter: SENT: 501 Invalid character in command
2020-10-30 07:49:45.750 12384-14355/com.amaze.filemanager.debug I/FtpLoggingFilter: CREATED
2020-10-30 07:49:45.753 12384-14352/com.amaze.filemanager.debug I/FtpLoggingFilter: OPENED
2020-10-30 07:49:45.763 12384-14351/com.amaze.filemanager.debug I/FtpLoggingFilter: SENT: 220 Service ready for new user.
2020-10-30 07:49:45.775 12384-14352/com.amaze.filemanager.debug I/FtpLoggingFilter: RECEIVED: USER anonymous
2020-10-30 07:49:45.786 12384-14351/com.amaze.filemanager.debug I/FtpLoggingFilter: SENT: 331 Guest login okay, send your complete e-mail address as password.
2020-10-30 07:49:45.797 12384-14352/com.amaze.filemanager.debug I/FtpLoggingFilter: RECEIVED: PASS *****
2020-10-30 07:49:45.805 12384-14352/com.amaze.filemanager.debug I/o*.a*.f*.c*.i*.PASS: Anonymous login success - User@
2020-10-30 07:49:45.810 12384-14351/com.amaze.filemanager.debug I/FtpLoggingFilter: SENT: 230 User logged in, proceed.
2020-10-30 07:49:45.819 12384-14352/com.amaze.filemanager.debug I/FtpLoggingFilter: RECEIVED: opts utf8 on
2020-10-30 07:49:45.828 12384-14351/com.amaze.filemanager.debug I/FtpLoggingFilter: SENT: 200 Command OPTS okay.
2020-10-30 07:49:45.835 12384-14352/com.amaze.filemanager.debug I/FtpLoggingFilter: RECEIVED: PWD
2020-10-30 07:49:45.844 12384-14351/com.amaze.filemanager.debug I/FtpLoggingFilter: SENT: 257 "/" is current directory.
2020-10-30 07:49:45.856 12384-14352/com.amaze.filemanager.debug I/FtpLoggingFilter: RECEIVED: DELE 道德經釋義_呂喦撰(掃葉山房重鐫本).djvu
2020-10-30 07:49:45.869 12384-14351/com.amaze.filemanager.debug I/FtpLoggingFilter: SENT: 450 Can't delete file /道德經釋義_呂喦撰(掃葉山房重鐫本).djvu.
2020-10-30 07:49:50.273 12384-14352/com.amaze.filemanager.debug I/FtpLoggingFilter: CLOSED
```

**Comment by TranceLove** [comment] 2020-10-30 03:29
Further analysis using the hex dump reported in the exception.

The hex dump
```
org.apache.mina.filter.codec.ProtocolDecoderException: java.nio.charset.MalformedInputException: Input length = 1 (Hexdump: 53 54 4F 52 20 E9 81 93 E5 BE B7 E7 B6 93 E9 87 8B E7 BE A9 5F E5 91 82 E5 96 A6 E6 92 B0 28 E6 8E 81 45 91 89 E5 B1 B1 E6 88 BF E9 87 8D E9 90 AB E6 9C AC 29 2E 64 6A 76 75 0D 0A)
```
was actually attempting to invoke FTP `STOR 道德經釋義_呂喦撰(掃葉山房重鐫本).djvu`, but Windows FTP client sent `STOR 道德經釋義_呂喦撰(掁E��山房重鐫本).djvu`, causing the error.

JVM reported the hex values of this string should be
```
53 54 4F 52 20 E9 81 93 E5 BE B7 E7 B6 93 E9 87 8B E7 BE A9 5F E5 91 82 E5 96 A6 E6 92 B0 28 E6 8E 83 E8 91 89 E5 B1 B1 E6 88 BF E9 87 8D E9 90 AB E6 9C AC 29 2E 64 6A 76 75
```

Main difference causing the string to corrupt is here.
Windows 8.1 said `E6 8E 83 E8 91 89` -> 掁E�� <- __String corrupted here__
JVM expected `E6 8E 81 45 91 89` -> 掃葉

Can't think of a better way to handle this, when Windows FTP client itself is sending unicode string in incorrect bytes... or is it related to byte order differences?

**Comment by TranceLove** [comment] 2020-11-24 14:18
I'm closing it, since we couldn't find a good way to deal with the incorrect unicode characters sent from Windows Explorer's FTP client, at least for now. It is probably some codepage differences between Windows and rest of the world, or it's simply a bug.

[At least we are not alone, too.](https://social.technet.microsoft.com/Forums/exchange/en-US/6b4df752-51d1-42fb-baf1-8600fa0bdfc5/utf8-encoding-bug-report-about-using-ftp-with-windows-explorer?forum=w7itpronetworking)

I'd recommend apps like Filezilla which will definitely work, plus FTPS (FTP over SSL) support.

If anyone knows how to fix this, feel free to send in your PR.

**Closed by TranceLove** 2020-11-24 14:18 UTC
Labels: Area-FTP, Issue-Bug

**Comment by VishalNehra** [comment] 2020-11-24 15:22
Maybe a  `help_needed` label then?
