### ISSUE TITLE
 After opening amaze for the second time, rotating the screen on the permission request box will eventually cause a crash

### ISSUE THREAD

**Issue by sjl872964789** [TeamAmaze/AmazeFileManager#1964] opened 2020-08-19 08:42 UTC
**Describe the bug**
I have reported some permissions issues before, they have been fixed well, but there are still some other permissions issues on the latest version.

**To Reproduce**
1. Install AmazeFileManager and open app
2. Close and re-open AmazeFileManager
3. The "grant permission" prompt box appears
4. Click on "GRANT"
5. The permission request box appears
6. Rotate screen
7. Click on "ALLOW"
8. The "grant permission" prompt box appears again
9. Click on "GRANT"
10. Crash
4. Black Screen

**Expected behavior**
Non crash

**Smartphone (please complete the following information):**
 - Device: HUAWEI nova 5 pro
 - OS: EMUI 9.1.1
 - Rooted: No
 - Version: v3.4.3

**Additional context**
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/15941953/90612380-870d5580-e23a-11ea-9d67-aadaee1dd6b9.gif)

**Comment by TranceLove** [comment] 2020-08-19 14:57
Duplicate of #1885.

It should have been fixed by #1893. Sorry we are still busy rushing for the next public beta... please be patient, or try pulling the latest `release/3.5` branch and see if the problem is fixed for you.

**Closed by TranceLove** 2020-08-19 14:57 UTC
