### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by MonikaJethani** [TeamAmaze/AmazeFileManager#1638] opened 2019-06-10 11:18 UTC
@EmmanuelMess  Can I work on migrating this project to AndroidX?

**Comment by VishalNehra** [comment] 2019-06-10 11:24
Please write it's pros and cons. I'm not updated with this. Also, what's your estimation is, how much code base would be required to change? Only import statements or API changes would be required anywhere?

**Comment by EmmanuelMess** [comment] 2019-06-10 16:27
API changes, for sure, I am not sure how drastical though. The support lib has been deprecated AFAIK, now AndroidX is the way.

**Comment by TranceLove** [comment] 2019-06-23 00:31
> API changes, for sure, I am not sure how drastical though. The support lib has been deprecated AFAIK, now AndroidX is the way.

I would say this is one of the reason to move to androidx.*. And we may begin from migrating deprecated libs to androidx.* first.

**Comment by EmmanuelMess** [comment] 2019-06-23 01:17
It shoudn't be THAT difficult to migrate, as the code is essentially the same, but more modular.

**Comment by MonikaJethani** [comment] 2019-06-24 10:21
@EmmanuelMess Can I work on this migration?

**Comment by TranceLove** [comment] 2019-06-24 11:01
@MonikaJethani feel free to go ahead.

**Comment by EmmanuelMess** [comment] 2019-06-24 13:52
@MonikaJethani remember that Android Studio has a button that does most of the work.

**Comment by EmmanuelMess** [comment] 2019-07-09 07:09
Duplicate of #1474.

**Closed by EmmanuelMess** 2019-07-09 07:09 UTC
