### ISSUE TITLE
Oreo icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [TeamAmaze/AmazeFileManager#1187] opened 2018-04-20 09:09 UTC
Please add support for icon shape
https://material.io/guidelines/style/icons.html

**Comment by lokesh-krishna** [comment] 2018-04-28 04:49
Duplicate of #1029?

**Comment by c-e-p-x-u-o** [comment] 2018-04-28 14:16
Yep!

**Comment by lokesh-krishna** [comment] 2018-04-28 14:29
Could you please close it then?

**Closed** 2018-04-28 14:36 UTC
Labels: bug
