### ISSUE TITLE
Support for USB File transfer

### ISSUE THREAD

**Issue by lukash** [TeamAmaze/AmazeFileManager#3586] opened 2022-10-22 13:09 UTC
**Is your feature request related to a problem? Please describe.**
Can't use Amaze for copying files between devices connected via the USB cable, the other device doesn't appear.

**Describe the solution you'd like**
I'd like the other device to appear in the hamburger menu under Bookmarks, so that I can access its files.

**Describe alternatives you've considered**
When connecting via USB and selecting File transfer, the "Files" app opens on "Device A". It has "Device A", as well as "Device B", in the hamburger menu and I can tap either to access the root of the storage of that device. It'd be really cool if Amaze worked the same.

**Comment by VishnuSanal** [comment] 2022-10-22 14:51
@lukash thanks for reaching out. is it that the device doesn't get recognized altogether or that it's unable to perform file transfer operation? also, are you trying to connect multiple USB devices (#2633)?

**Comment by lukash** [comment] 2022-10-23 09:53
> is it that the device doesn't get recognized altogether or that it's unable to perform file transfer operation?

The device doesn't show up in Amaze. I wouldn't say "doesn't get recognized", as it shows up in the "Files" app (which pops up automatically after enabling file transfer). I'd just prefer to do this in Amaze. Since it doesn't show up, I can't do the copy operation in Amaze, but it works in "Files" just fine.

> also, are you trying to connect multiple USB devices (#2633)?

I'm not and AFAICT there's no other storage connected, the phone doesn't have an sdcard either.

From your questions and also from reading the other bug it seems this is expected to work?

To provide more info this is connecting Asus Zenfone 9 with stock Android 12 to Oneplus 3t with NitrogenOS Android 10 using a USB-C data cable.

**Comment by VishnuSanal** [comment] 2022-10-23 17:02
@TranceLove ping :)

**Comment by TranceLove** [comment] 2022-10-24 09:28
Yeap, somebody did suggested so a while ago. #1820.

But I have to say, even without Amaze and use stock file manager alone, I find it sometimes it's difficult to know which is master and which is slave... but it's Android's own problem.

Thanks for the suggestion anyway - but it's duplicate of #1820.

**Closed by TranceLove** 2022-10-24 09:28 UTC
Labels: Area-USB

**Comment by lukash** [comment] 2022-10-24 10:42
> But I have to say, even without Amaze and use stock file manager alone, I find it sometimes it's difficult to know which is master and which is slave... but it's Android's own problem.

I've had the same issue, couldn't change which one is master. But yeah I'd much rather use Amaze.
