### ISSUE TITLE
Crash when USB Drive is attached

### ISSUE THREAD

**Issue by computerJoe** [TeamAmaze/AmazeFileManager#2153] opened 2020-12-17 01:58 UTC
## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.2
* __OS:__ Linux Android 10 - 29
* __Device:__ OnePlus7Pro
* __Model:__ GM1917
* __Product:__ OnePlus7Pro
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to resume activity {com.amaze.filemanager/com.amaze.filemanager.ui.activities.MainActivity}: java.lang.SecurityException: User has not given 10282/com.amaze.filemanager permission to access device /dev/bus/usb/001/002
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4336)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4368)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.SecurityException: User has not given 10282/com.amaze.filemanager permission to access device /dev/bus/usb/001/002
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.hardware.usb.IUsbSerialReader$Stub$Proxy.getSerial(IUsbSerialReader.java:123)
	at android.hardware.usb.UsbDevice.getSerialNumber(UsbDevice.java:143)
	at com.amaze.filemanager.utils.OTGUtil.getMassStorageDevicesConnected(OTGUtil.java:168)
	at com.amaze.filemanager.ui.activities.MainActivity.updateUsbInformation(MainActivity.java:1203)
	at com.amaze.filemanager.ui.activities.MainActivity.onResume(MainActivity.java:1195)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1560)
	at android.app.Activity.performResume(Activity.java:7957)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4326)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.usb.UsbUserSettingsManager.checkPermission(UsbUserSettingsManager.java:177)
	at com.android.server.usb.UsbSerialReader.getSerial(UsbSerialReader.java:96)
	at android.hardware.usb.IUsbSerialReader$Stub.onTransact(IUsbSerialReader.java:84)
	at android.os.Binder.execTransactInternal(Binder.java:1032)
	at android.os.Binder.execTransact(Binder.java:1005)


```
</details>
<hr>

**Comment by TranceLove** [comment] 2020-12-17 02:49
Duplicate of #2148.

**Closed by TranceLove** 2020-12-17 02:49 UTC
