### ISSUE TITLE
Smb links are unsuccessful

### ISSUE THREAD

**Issue by wanglefeifei** [TeamAmaze/AmazeFileManager#1653] opened 2019-07-24 08:07 UTC
https://github.com/wanglefeifei/react-native-demo/blob/master/20190724160004.jpg

**Comment by wanglefeifei** [comment] 2019-07-24 08:10
You can't always search for devices, but ES can.

**Comment by EmmanuelMess** [comment] 2019-07-24 17:06
Can you provide the link?

**Comment by wanglefeifei** [comment] 2019-07-25 06:02
> Can you provide the link?

waht link?

**Comment by TranceLove** [comment] 2019-07-27 07:55
I think he means SMB auto discovery was not successful?

**Comment by wanglefeifei** [comment] 2019-07-29 02:26
> I think he means SMB auto discovery was not successful?

yes,Did you meet too?

**Comment by TranceLove** [comment] 2019-07-29 04:06
Should have been. But I usually enter the IP address on my own, so not a big problem for me.

**Comment by wanglefeifei** [comment] 2019-07-29 09:57
> Should have been. But I usually enter the IP address on my own, so not a big problem for me.

Why can't I play the video six minutes after I connect to smb?

**Comment by wanglefeifei** [comment] 2019-07-30 02:30
> Should have been. But I usually enter the IP address on my own, so not a big problem for me.

Hey, is my brother still there?

**Comment by TranceLove** [comment] 2019-07-30 03:12
> > Should have been. But I usually enter the IP address on my own, so not a big problem for me.
> 
> Why can't I play the video six minutes after I connect to smb?

Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...

BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.

**Comment by wanglefeifei** [comment] 2019-07-30 03:33
> Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...
> 
> BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.

The SMB link was successful and the video was played for 6 minutes. It will disconnect automatically.

**Comment by wanglefeifei** [comment] 2019-07-30 03:35
> > > Should have been. But I usually enter the IP address on my own, so not a big problem for me.
> > 
> > 
> > Why can't I play the video six minutes after I connect to smb?
> 
> Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...
> 
> BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.

Have you ever been in this situation?

**Comment by TranceLove** [comment] 2019-07-30 03:52
> > > > Should have been. But I usually enter the IP address on my own, so not a big problem for me.
> > > 
> > > 
> > > Why can't I play the video six minutes after I connect to smb?
> > 
> > 
> > Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...
> > BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.
> 
> Have you ever been in this situation?

Never been doing this (I use Amaze mainly on retrieving files over SSH instead), but let's check.

**Comment by wanglefeifei** [comment] 2019-07-30 10:52
> > > > > Should have been. But I usually enter the IP address on my own, so not a big problem for me.
> > > > 
> > > > 
> > > > Why can't I play the video six minutes after I connect to smb?
> > > 
> > > 
> > > Are you streaming videos over SMB? But I'm sorry that I may not be very helpful here...
> > > BTW, you may want to raise a new issue with details of the symptom, so we/contributors will have more information to help, and focus on the symptom itself.
> > 
> > 
> > Have you ever been in this situation?
> 
> Never been doing this (I use Amaze mainly on retrieving files over SSH instead), but let's check.

Have you encountered this problem?

**Comment by EmmanuelMess** [comment] 2019-08-11 16:56
I'll close this as it is dupe of #1654

**Closed by EmmanuelMess** 2019-08-11 16:56 UTC
Labels: bug, test on master
