### ISSUE TITLE
crash on PASTE to SDcard

### ISSUE THREAD

**Issue by aplatypus** [TeamAmaze/AmazeFileManager#2144] opened 2020-12-14 23:16 UTC
**Describe the bug**
Selected s file.
Press COPY
Moved todestinstion directory
pressed PASTE

## Exception
* __User Action:__ UI Error
* __Request:__ Application crash
* __Version:__ 3.5.2
* __OS:__ Linux Android 10 - 29
* __Device:__ a70q
* __Model:__ SM-A705YN
* __Product:__ a70qdo
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'androidx.documentfile.provider.DocumentFile androidx.documentfile.provider.DocumentFile.findFile(java.lang.String)' on a null object reference
	at com.amaze.filemanager.filesystem.FileUtil.getDocumentFile(FileUtil.java:949)
	at com.amaze.filemanager.filesystem.FileUtil.isWritableNormalOrSaf(FileUtil.java:806)
	at com.amaze.filemanager.utils.MainActivityHelper.checkFolder(MainActivityHelper.java:414)
	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.finishCopying(PrepareCopyTask.java:325)
	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.onEndDialog(PrepareCopyTask.java:275)
	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.onEndDialog(PrepareCopyTask.java:269)
	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.onPostExecute(PrepareCopyTask.java:186)
	at com.amaze.filemanager.asynchronous.asynctasks.PrepareCopyTask.onPostExecute(PrepareCopyTask.java:64)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

```
</details>
<hr>

**Comment by EmmanuelMess** [comment] 2020-12-16 20:15
Dupe of  #2142.

**Closed by EmmanuelMess** 2020-12-16 20:15 UTC
