### ISSUE TITLE
Failed to copy a large file from smb server

### ISSUE THREAD

**Issue by sc104501** [TeamAmaze/AmazeFileManager#1802] opened 2019-12-28 11:19 UTC
**Describe the bug**
When I try to copy a large file(more than 1GB) from smb server, app will pop a window about “operation failed”

**To Reproduce**
1. Go to smb server
2. Copy a big file
3. Paste to local storage

**Smartphone (please complete the following information):**
 - Device: Xiaomi Note 3
 - OS: Android9 MIUI.EU 11
 - Rooted: Yes
 - Version: 3.3.4

**Additional context**
Logcat:
`
12-28 18:59:21.445  7133  7133 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
12-28 18:59:23.771  7133  7328 D skia    : --- Failed to create image decoder with message 'unimplemented'
12-28 18:59:23.784  7133  7133 W Glide   : Load failed for smb://****:******@smb_path/a_big_file with size [110x110]
12-28 18:59:23.784  7133  7133 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
12-28 18:59:23.806  7133  7329 D skia    : --- Failed to create image decoder with message 'unimplemented'
12-28 18:59:23.808  7133  7329 I chatty  : uid=10230(com.amaze.filemanager) glide-source-th identical 2 lines
12-28 18:59:23.808  7133  7329 D skia    : --- Failed to create image decoder with message 'unimplemented'
12-28 18:59:27.499  7133  7133 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
12-28 18:59:27.593  7133  7133 D TabFragment: Page Selected: 0
12-28 18:59:29.852  7133  7133 W Choreographer: OPTS_INPUT: First frame was drawed before optimized, so skip!
12-28 18:59:30.667  7133 15143 W System.err: java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
12-28 18:59:30.667  7133 15143 W System.err:    at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:908)
12-28 18:59:30.667  7133 15143 W System.err:    at com.amaze.filemanager.utils.files.GenericCopyUtil.copyFile(GenericCopyUtil.java:331)
12-28 18:59:30.667  7133 15143 W System.err:    at com.amaze.filemanager.utils.files.GenericCopyUtil.startCopy(GenericCopyUtil.java:276)
12-28 18:59:30.667  7133 15143 W System.err:    at com.amaze.filemanager.utils.files.GenericCopyUtil.copy(GenericCopyUtil.java:325)
12-28 18:59:30.667  7133 15143 W System.err:    at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.copyFiles(CopyService.java:483)
12-28 18:59:30.667  7133 15143 W System.err:    at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground$Copy.execute(CopyService.java:387)
12-28 18:59:30.667  7133 15143 W System.err:    at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:260)
12-28 18:59:30.667  7133 15143 W System.err:    at com.amaze.filemanager.asynchronous.services.CopyService$DoInBackground.doInBackground(CopyService.java:224)
12-28 18:59:30.667  7133 15143 W System.err:    at android.os.AsyncTask$2.call(Unknown Source:20)
12-28 18:59:30.667  7133 15143 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-28 18:59:30.667  7133 15143 W System.err:    at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
12-28 18:59:30.667  7133 15143 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-28 18:59:30.667  7133 15143 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-28 18:59:30.667  7133 15143 W System.err:    at java.lang.Thread.run(Thread.java:764)
12-28 18:59:30.668  7133 15143 E CopyService: Got exception checkout: smb://****:******@smb_path/a_big_file
12-28 18:59:30.885  7133  7325 D skia    : --- Failed to create image decoder with message 'unimplemented'
12-28 18:59:30.888  7133  7325 I chatty  : uid=10230(com.amaze.filemanager) glide-source-th identical 2 lines
12-28 18:59:30.889  7133  7325 D skia    : --- Failed to create image decoder with message 'unimplemented'
12-28 18:59:30.916  7133  7188 D skia    : --- Failed to create image decoder with message 'unimplemented'
12-28 18:59:30.932  7133  7133 W Glide   : Load failed for /local_path/a_big_file with size [110x110]
12-28 18:59:30.932  7133  7133 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
12-28 18:59:30.932  7133  7133 W Glide   : There were 3 causes:
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   :  call GlideException#logRootCauses(String) for more detail
12-28 18:59:30.932  7133  7133 W Glide   :   Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Object->Drawable}, LOCAL
12-28 18:59:30.932  7133  7133 W Glide   :     Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->GifDrawable->Drawable}
12-28 18:59:30.932  7133  7133 W Glide   :     Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Drawable}
12-28 18:59:30.932  7133  7133 W Glide   :     Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->BitmapDrawable->Drawable}
12-28 18:59:30.932  7133  7133 W Glide   :   Cause (2 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Object->Drawable}, LOCAL
12-28 18:59:30.932  7133  7133 W Glide   : There were 2 causes:
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   :  call GlideException#logRootCauses(String) for more detail
12-28 18:59:30.932  7133  7133 W Glide   :     Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Drawable}
12-28 18:59:30.932  7133  7133 W Glide   : There was 1 cause:
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   :  call GlideException#logRootCauses(String) for more detail
12-28 18:59:30.932  7133  7133 W Glide   :       Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status 
12-28 18:59:30.932  7133  7133 W Glide   :     Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->BitmapDrawable->Drawable}
12-28 18:59:30.932  7133  7133 W Glide   : There was 1 cause:
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   :  call GlideException#logRootCauses(String) for more detail
12-28 18:59:30.932  7133  7133 W Glide   :       Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status
12-28 18:59:30.932  7133  7133 W Glide   :   Cause (3 of 3): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{AssetFileDescriptor->Object->Drawable}, LOCAL
12-28 18:59:30.932  7133  7133 W Glide   : There was 1 cause:
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   :  call GlideException#logRootCauses(String) for more detail
12-28 18:59:30.932  7133  7133 W Glide   :     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{AssetFileDescriptor->Bitmap->Drawable}
12-28 18:59:30.932  7133  7133 W Glide   : There was 1 cause:
12-28 18:59:30.932  7133  7133 W Glide   : java.io.IOException(java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA)
12-28 18:59:30.932  7133  7133 W Glide   :  call GlideException#logRootCauses(String) for more detail
12-28 18:59:30.932  7133  7133 W Glide   :       Cause (1 of 1): class java.io.IOException: java.lang.RuntimeException: setDataSource failed: status
12-28 18:59:30.932  7133  7133 I Glide   : Root cause (1 of 3)
12-28 18:59:30.932  7133  7133 I Glide   : java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:173)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:507)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:472)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:458)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:410)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:135)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:135)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
12-28 18:59:30.932  7133  7133 I Glide   :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-28 18:59:30.932  7133  7133 I Glide   :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-28 18:59:30.932  7133  7133 I Glide   :      at java.lang.Thread.run(Thread.java:764)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
12-28 18:59:30.932  7133  7133 I Glide   : Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
12-28 18:59:30.932  7133  7133 I Glide   :      at android.media.MediaMetadataRetriever.setDataSource(Native Method)
12-28 18:59:30.932  7133  7133 I Glide   :      at android.media.MediaMetadataRetriever.setDataSource(Unknown Source:9)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:296)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:291)
12-28 18:59:30.932  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:161)
12-28 18:59:30.932  7133  7133 I Glide   :      ... 30 more
12-28 18:59:30.933  7133  7133 I Glide   : Root cause (2 of 3)
12-28 18:59:30.933  7133  7133 I Glide   : java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:173)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.BitmapDrawableDecoder.decode(BitmapDrawableDecoder.java:58)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:507)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:472)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:458)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:410)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:135)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:135)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
12-28 18:59:30.933  7133  7133 I Glide   :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-28 18:59:30.933  7133  7133 I Glide   :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-28 18:59:30.933  7133  7133 I Glide   :      at java.lang.Thread.run(Thread.java:764)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
12-28 18:59:30.933  7133  7133 I Glide   : Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
12-28 18:59:30.933  7133  7133 I Glide   :      at android.media.MediaMetadataRetriever.setDataSource(Native Method)
12-28 18:59:30.933  7133  7133 I Glide   :      at android.media.MediaMetadataRetriever.setDataSource(Unknown Source:9)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:296)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder$ParcelFileDescriptorInitializer.initialize(VideoDecoder.java:291)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:161)
12-28 18:59:30.933  7133  7133 I Glide   :      ... 31 more
12-28 18:59:30.933  7133  7133 I Glide   : Root cause (3 of 3)
12-28 18:59:30.933  7133  7133 I Glide   : java.io.IOException: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:173)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decodeResourceWithList(DecodePath.java:72)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decodeResource(DecodePath.java:55)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodePath.decode(DecodePath.java:45)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.LoadPath.loadWithExceptionList(LoadPath.java:58)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.LoadPath.load(LoadPath.java:43)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runLoadPath(DecodeJob.java:507)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromFetcher(DecodeJob.java:472)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromData(DecodeJob.java:458)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:410)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:135)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.decodeFromRetrievedData(DecodeJob.java:418)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.onDataFetcherReady(DecodeJob.java:379)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.onDataReady(SourceGenerator.java:112)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onDataReady(MultiModelLoader.java:135)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.data.LocalUriFetcher.loadData(LocalUriFetcher.java:52)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
12-28 18:59:30.933  7133  7133 I Glide   :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-28 18:59:30.933  7133  7133 I Glide   :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-28 18:59:30.933  7133  7133 I Glide   :      at java.lang.Thread.run(Thread.java:764)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
12-28 18:59:30.933  7133  7133 I Glide   : Caused by: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
12-28 18:59:30.933  7133  7133 I Glide   :      at android.media.MediaMetadataRetriever.setDataSource(Native Method)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder$AssetFileDescriptorInitializer.initialize(VideoDecoder.java:286)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder$AssetFileDescriptorInitializer.initialize(VideoDecoder.java:281)
12-28 18:59:30.933  7133  7133 I Glide   :      at com.bumptech.glide.load.resource.bitmap.VideoDecoder.decode(VideoDecoder.java:161)
12-28 18:59:30.933  7133  7133 I Glide   :      ... 36 more
12-28 18:59:30.933  7133  7133 W Glide   : Load failed for smb://****:******@smb_path/a_big_file with size [110x110]
12-28 18:59:30.933  7133  7133 W Glide   : class com.bumptech.glide.load.engine.GlideException: Failed to load resource
12-28 18:59:30.938  7133  7328 D skia    : --- Failed to create image decoder with message 'unimplemented'
12-28 18:59:30.939  7133  7328 I chatty  : uid=10230(com.amaze.filemanager) glide-source-th identical 2 lines
12-28 18:59:30.939  7133  7328 D skia    : --- Failed to create image decoder with message 'unimplemented'
`

**Comment by EmmanuelMess** [comment] 2020-02-15 01:10
ping @TranceLove.

**Comment by TranceLove** [comment] 2020-02-16 14:17
Getting the same problem, using LG Nexus 5x running AOSPExtended (9.0) to copy an Ubuntu ISO over SMB, with Linux Mint Tricia (= Ubuntu 18.04) + Samba 4.7.6.

Copy process stopped in the middle of nowhere. But just the progress dialog stopped. If I keep refreshing the file list I still can see the ISO file growing in size.

I did saw messages like this coming up.

```

2020-02-16 22:02:57.951 752-752/? W/Looper: Slow dispatch took 123ms main h=com.android.server.notification.NotificationManagerService$WorkerHandler c=com.android.server.notification.NotificationManagerService$PostNotificationRunnable@7037383 m=0
2020-02-16 22:02:58.079 3801-3813/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 124)
2020-02-16 22:02:58.079 2844-2859/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 124)
2020-02-16 22:02:58.080 3801-3813/? W/NotificationListener: onNotificationPosted: Error receiving StatusBarNotification
    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1129)
        at android.service.notification.IStatusBarNotificationHolder$Stub$Proxy.get(IStatusBarNotificationHolder.java:90)
        at android.service.notification.NotificationListenerService$NotificationListenerWrapper.onNotificationPosted(NotificationListenerService.java:1226)
        at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:72)
        at android.os.Binder.execTransact(Binder.java:731)
2020-02-16 22:02:58.080 2844-2859/? W/NotificationListener: onNotificationPosted: Error receiving StatusBarNotification
    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1129)
        at android.service.notification.IStatusBarNotificationHolder$Stub$Proxy.get(IStatusBarNotificationHolder.java:90)
        at android.service.notification.NotificationListenerService$NotificationListenerWrapper.onNotificationPosted(NotificationListenerService.java:1226)
        at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:72)
        at android.os.Binder.execTransact(Binder.java:731)
2020-02-16 22:02:58.758 10268-10823/com.amaze.filemanager.debug E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1040288)
```

The Glide error message @sc104501 mentioned was not of utmost concern, as they imply problem fetching file icons in the file list.

**Comment by TranceLove** [comment] 2021-01-05 05:16
Tried again with current codebase, copied a 1.98GB video to Pixel 4 emulator running Android 10 and Fairphone 3 running LineageOS 16.0(9.0) to both internal and external storage (SD card) separately, all completed successfully without error.

I'll be closing this for now. Please try with the latest 3.5 series and see if the problem is gone.

**Closed by TranceLove** 2021-01-05 05:16 UTC
Labels: Area-SMB, Issue-Bug
