### ISSUE TITLE
Add WebDAV, Nextcloud / own cloud support

### ISSUE THREAD

**Issue by scanno** [TeamAmaze/AmazeFileManager#804] opened 2017-10-19 18:44 UTC
A good enhancement for the cloud plugin would be to add support for WebDAV and also for Nextcloud/ownCloud that are WebDAV based.

Apologies if this enhancement was already mentioned.

**Comment by DJCrashdummy** [comment] 2018-02-02 22:43
this is a duplicate of #376.

**Comment by EmmanuelMess** [comment] 2018-02-02 23:02
I'd say related #376.

**Closed** 2022-08-28 21:39 UTC
Labels: Issue-Feature, help wanted
