### ISSUE TITLE
Cannot delete in 'Android/' directory

### ISSUE THREAD

**Issue by tenzap** [TeamAmaze/AmazeFileManager#3828] opened 2023-05-29 11:42 UTC
**Describe the bug**
I'm trying to delete a subfolder of the Android directory on the built-in device directory.
It doesn't get deleted.

**To Reproduce**
1. Select the built in Device root 
2. Go to the Android folder, select a package in that folder and a subdir of that package 
3. Delete the folder
4. It says it is deleting but in fact nothing happens 

**Expected behavior**
dir should be deleted

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi note 9s
 - OS: Android 12
 - Rooted:  No
 - Version: amaze 3.8.5

**Comment by VishnuSanal** [comment] 2023-06-04 07:36
hi, I tried to reproduce the issue on an emulator (Pixel 3A with API 31) & it worked fine. I was able to delete a child directory of `Android/data/com.google.android.docs`. I tried on `Android/media` & that worked too. I wasn't able to delete `Android/obb` though. please confirm these were the steps you followed.

PS: ping @TranceLove

**Comment by VishalNehra** [comment] 2023-06-04 11:15
> * navigation is very slow inside Android

It's going to be slow since Google put restrictions on accessing Android/ directory by any third party apps. 
The late deletion part might be an issue since we receive event to update the directory while it's still in process of deletion. That might be the reason you still see the directory and requires an extra step to refresh / go back to parent directory. 
We'll track that as a part of different issue #3839 , however since the original issue for this is not reproducible we'll close this one. 
Thanks for reportin! :)

**Closed by VishalNehra** 2023-06-04 11:15 UTC
Labels: Needs-OPResponse
