### ISSUE TITLE
Is Amaze now Non-free software.

### ISSUE THREAD

**Issue by Oymate** [TeamAmaze/AmazeFileManager#1889] opened 2020-05-12 12:29 UTC
On F-droid it says that the source code of Amaze is no longer availiable. Can you resolve this?

**Comment by TranceLove** [comment] 2020-05-12 12:41
Duplicate of #1593 and #1886

**Comment by Oymate** [comment] 2020-05-12 17:02
Thanks.

**Closed** 2020-05-12 17:03 UTC
