### ISSUE TITLE
Root folder issue

### ISSUE THREAD

**Issue by ghost** [TeamAmaze/AmazeFileManager#1423] opened 2018-08-26 11:19 UTC
If the device back button is *repeatedly* pressed from a directory in the **internal** or **external storage**, this app takes me to the **root folder system**, even though **root fille explorer option is **checked off**. It is **expected** from it to take me to the **main internal/external storage folder (home folder)**, not the root folder.

**Comment by VishalNehra** [comment] 2018-11-02 19:40
@EmmanuelMess should we transfer this issue to next release?

**Comment by EmmanuelMess** [comment] 2018-11-03 00:37
@VishalNehra yeah, sorry.

We should discuss where "root" starts, say if I am in a random folder, how do I decide if I am in root?

**Comment by shizunge** [comment] 2019-01-13 22:06
I am using 3.3.2. and I do not see this is solved.
For example, I am using a non-root device, and my storage is at "/storage/emulated/0".
It make no sense go to "/storage/emulated", "/storage" or "/", because anything outside my internal storage is inaccessible to me.
My internal storage "/storage/emulated/0" should be my virtual root. (BTW, my device does not support external storage)

Current behavior is when I am at "/storage/emulated/0", I can still go back to one level above, until reaching "/"

**Comment by EmmanuelMess** [comment] 2019-01-15 20:20
> I am using 3.3.2. and I do not see this is solved.

It is not.

**Comment by VishalNehra** [comment] 2020-07-16 13:02
Duplicate of #1919

**Closed by VishalNehra** 2020-07-16 13:02 UTC
Labels: Issue-Bug
