### ISSUE TITLE
Sort Apps by User and System Apps in app manager

### ISSUE THREAD

**Issue by ghost** [TeamAmaze/AmazeFileManager#1431] opened 2018-09-02 22:01 UTC
1. Please group the apps under **user** and **system** label for easy access.
~2. Please add a **quick scrollbar** in the text editor. It really **helps to go and edit the last lines of a very very long text** in an instance. (Probably I could not explain it earlier)~

P. S. Sorry for the spelling mistakes in my previous comments.

**Comment by EmmanuelMess** [comment] 2018-09-02 22:42
Please, one enhancement per issue, and enhancement 2 is duplicate of #1422.

**Comment by pcsaunak** [comment] 2020-07-17 07:53
@EmmanuelMess @VishalNehra Do you guys mind putting a bit more context to this issue ?

**Comment by EmmanuelMess** [comment] 2020-07-25 12:40
@pcsaunak In the app manager, drawer.

**Comment by prafullmishra** [comment] 2020-08-16 16:54
@EmmanuelMess to be clear, the app list shown when the user selects **App Manager** from the left drawer, to that list only this categorization or label needs to be added. Right? If so, I can pick this up.

**Comment by VishalNehra** [comment] 2020-08-16 17:07
From what I can understand, a label like 'System Apps' and 'User Apps' in app drawer list, similar to 'Files' and 'Folders' labels in storage tabs.

**Comment by prafullmishra** [comment] 2020-08-16 17:10
Cool. Thanks for clarifying. So should I pick this up? If no one else is assigned to the same?

**Comment by VishalNehra** [comment] 2020-08-16 17:24
Sure.. no one has picked this up I think.. can ping on group as well (: to take their views here.

**Comment by sachin-0102** [comment] 2020-08-18 09:54
Can I work on this issue?

**Comment by TranceLove** [comment] 2020-08-18 10:15
Contributions are always welcomed! Be sure to read [contribution guidelines](https://github.com/TeamAmaze/AmazeFileManager/blob/release/3.5/CONTRIBUTING.md) when you work on it too.

**Comment by VishalNehra** [comment] 2020-08-18 11:10
Two people working on same issue is not ideal. Please join our Telegram link and we shall discuss on issue assignment @sachin-0102 
https://t.me/joinchat/NNFgWxQUB8fFE3yCsC0w4g

**Closed** 2021-10-10 23:45 UTC
Labels: Issue-Feature, good first issue, Area-AppManager
