### ISSUE TITLE
Amaze not showing-up in File-manager suggestions

### ISSUE THREAD

**Issue by aha999** [TeamAmaze/AmazeFileManager#1838] opened 2020-02-15 13:54 UTC
**Describe the bug**
When i select to send a file over [Signal](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms), only stock file manager and Material Files file manager pop-up as options, but no Amaze.

**To Reproduce**
1. Open Signal secure messenger (or probably any app that can pop-up file manager programs)
2. Click on person you want to text
3. click on + button
4. Select Files
5. See file managers pop-up except Amaze file manager

**Expected behavior**
Amaze file manager should be among other file manager suggestions.

**Smartphone (please complete the following information):**
 - Device: Lenovo P2
 - OS: Android 9 (LineageOS 16)
 - Rooted: No
 - Version: 3.4.2

**Comment by TranceLove** [comment] 2020-02-26 06:51
Seems to be caused by missing handling for [android.intent.action.OPEN_DOCUMENT](http://www.openintents.org/action/android-intent-action-open-document/) and [org.openintents.action.PICK_FILE](http://www.openintents.org/action/org-openintents-action-pick-file/) intents.

**Comment by VishalNehra** [comment] 2021-11-13 13:52
This should be fixed.

**Closed by VishalNehra** 2021-11-13 13:52 UTC
Labels: Issue-Bug, Area-Sharing
