### ISSUE TITLE
Paste Icon Remains when Deleting a Copied File

### ISSUE THREAD

**Issue by thewizardstudio** [TeamAmaze/AmazeFileManager#952] opened 2018-01-23 03:17 UTC
#### Expected Behavior
Copying a File and then Deleting that same File should either clear the Clipboard if a Paste process cannot be supported when the original File is missing, or the Paste process should still be possible without the original File present.

#### Actual Behavior
Copying a File and then Deleting that same file does not cause the Clipboard icon to disappear, which gives the user the impression there is still something to Paste.  When the User attempts to Paste the Copied file, they will receive an error. 

#### How to Reproduce
1. Launch Amaze File Manager 3.2.1 on Android 8.1.0
2. Click the 3 Vertical Dots icon to the right of a File
3. Select 'Copy'
4. Click the 3 Vertical Dots icon to the right of the Copied File
6. Select 'Delete'
7. Select 'Delete' on the Dialogue Window
8. Click the Clipboard Icon in the Upper Right

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.2.1
---

#### Recording of the Bug
![PastingADeletedFileError.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516244791/sxth4wrktvaefqogkos3.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/paste-icon-remains-when-deleting-a-copied-file">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by EmmanuelMess** [comment] 2018-01-23 03:42
Duplicate of #676

**Closed by EmmanuelMess** 2018-01-23 03:42 UTC
