### ISSUE TITLE
Can't specify apps to open files any more

### ISSUE THREAD

**Issue by akkana** [TeamAmaze/AmazeFileManager#816] opened 2017-11-04 02:24 UTC
I use Amaze as a file picker: navigate to a file and open it in the appropriate app. It's been working great for most of a year, best file picker I've seen.
Something changed recently -- it might have been an Amaze update, or it might have been because I installed a system upgrade for my phone (Samsung Galaxy S5, Marshmallow), but I've lost the ability to choose which app to open files with.

If I try to open a .mp3 file, Amaze used to ask me what app to use, and I could choose a music player app. Now it opens Audible, which I've never run before for any reason and don't want to use.

When I tap on a .gpx file (an XML format) and tap on Other hoping to get the chance to choose OsmAnd, I see:
```
Parse error
There was a problem parsing the package
```
I don't need anything parsed, I just want to specify an app to use to open the file.

I may have a clue. If I run adb logcat | egrep --line-buffered -i gpx and choose a gpx file, I see:

```
11-03 20:18:13.051 26051 26051 D         : Zip: EOCD not found, /storage/nnnn-nnnn/GPX/ponderosa.gpx is not zip
11-03 20:18:13.051 26051 26051 W zipro   : Error opening archive /storage/nnnn-nnnn/GPX/ponderosa.gpx: Invalid file
11-03 20:18:13.051 26051 26051 D asset   : failed to open Zip archive '/storage/nnnn-nnnn/GPX/ponderosa.gpx'
11-03 20:18:13.061 26051 26051 D asset   : failed to close Zip archive '/storage/nnnn-nnnn/GPX/ponderosa.gpx'
```

GPX is not a zipped format, it's straight XML I can open the file in amaze's text editor and see the XML. So maybe the problem is in Zip format detection.

I just tried installing fx file explorer, and tapping on a gpx file in fx opened it in OsmAnd right away without my needing to choose an app or worrying about whether it's zipped. Is there a way I can get Amaze to do that? Or at least get it to go back to letting me choose an app through Other...?

**Comment by VishalNehra** [comment] 2017-11-04 20:00
You can try using 'Open with' from three dot menu in front of file.

**Comment by akkana** [comment] 2017-11-05 15:58
Open With from the ... menu on a GPX just leads to the same Open As menu, where I choose Other and it gives me the Parse Error.

On an MP3, the ... menu doesn't even offer Open With. It has Cut, Copy, Delete, Rename, Encrypt, Properties and Add to Bookmark.

**Comment by meiser79** [comment] 2017-12-26 13:03
I have a similiar issue with the app since some days. When I try to open a file, I get "No App found to open this file" even though a suitable app is available. I can reproduce it with txt and pdf files.

**Comment by trevor87** [comment] 2018-01-05 16:03
Hi everyone!

I am also having a issue with the "open with" dialog: Everytime I try to open a mp3 file the "open with" dialog opens and I select "open with vlc everytime" but I get asked the same question the next time I open a mp3 file again. When I use the built in filemanager for lineage os I do not get this behaviour: It stores my "open with" setting. I use Lineage OS 14.1 = Android 7.1.2

Please let me know if you need further debug information.

Thanks for all the good work!

**Comment by VishalNehra** [comment] 2018-01-08 11:11
@trevor87 your issue is not related to this one. My best guess is, it's a framework issue. I'd ask your ROM developer for the fix.

**Comment by trevor87** [comment] 2018-01-11 20:59
@VishalNehra Thanks for your answer!

Do you think it is a framework issue, even though the built in file manager shows the expected behaviour?

**Comment by trevor87** [comment] 2019-02-17 12:39
> @trevor87 your issue is not related to this one. My best guess is, it's a framework issue. I'd ask your ROM developer for the fix.

Hi @VishalNehra 

a quick update on this: As I got a new phone now (Pixel Phone with Googles Android 9) I tried Amaze out again. The problem that Amaze does not save which app to open a file with persists. So it seems that it is a problem with Amaze and not the operating system. The built in Android File manager does not have this problem.

**Comment by VishalNehra** [comment] 2021-07-17 11:11
This should've been fixed now. update to latest v3.6.1

**Closed by VishalNehra** 2021-07-17 11:11 UTC
Labels: Issue-Bug
