### ISSUE TITLE
Amaze don't recognize 7z compressed files

### ISSUE THREAD

**Issue by B4rabbas** [TeamAmaze/AmazeFileManager#1019] opened 2018-02-12 12:43 UTC
Hello,
Can you add support for 7z files for extraction and compression. This one is a very usefull file format and libre.
Many thanks.
Best regards.
B.

**Comment by EmmanuelMess** [comment] 2018-02-12 15:01
Duplicate of #163

**Closed by EmmanuelMess** 2018-02-12 15:01 UTC
