### ISSUE TITLE
App drawer does not show up properly in landscape mode

### ISSUE THREAD

**Issue by pcsaunak** [TeamAmaze/AmazeFileManager#1967] opened 2020-08-20 08:18 UTC
**Describe the bug**
In landscape mode, it shows strange behaviour. Refer the attached image.
![Screenshot_20200820-134539](https://user-images.githubusercontent.com/23631671/90737784-d3fd3480-e2eb-11ea-8c63-d96fc151e6a4.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 7t
 - OS: Android 10
 - Rooted: No

**Additional context**

**Comment by VishalNehra** [comment] 2020-08-25 13:11
Duplicate of #1061

**Closed by VishalNehra** 2020-08-25 13:11 UTC
Labels: Area-UIUX, Duplicate, Issue-Task (low)
