### ISSUE TITLE
SMB not finding Servers automatically

### ISSUE THREAD

**Issue by DennisHackerman** [TeamAmaze/AmazeFileManager#3386] opened 2022-07-03 23:10 UTC
Hey!
I want to report a bug. I host a SMB file server on my own network and when searching/accessing it with another Windows machine, everything works great. It gets detected automatically in the "Network"-Section in file explorer. However, when I try to find it using the "+"-Button on the lower right, selecting "Cloud Connection" and then "SMB Connection", it didn't show up after letting the app search for 3 minutes.
I am on Android 12L (LineageOS 19.1) and use the latest version of Amaze File Explorer provided by the Google Play Store.

**Comment by NanyangTaiji** [comment] 2022-07-05 01:46
Never worked for me.

**Comment by TranceLove** [comment] 2022-07-05 02:38
@NanyangTaiji Possible duplicate of #2622

I share the pain with you, but never been able to get a good solution for SMBv2 server discovery. I too need someone to shed some light on how SMBv2 is doing, so we can fix this long overdue problem.

**Comment by fiasko131** [comment] 2022-07-14 17:33
@TranceLove 
For that you can use this:
https://github.com/stealthcopter/AndroidNetworkTools
````java
ArrayList<Integer> ports = new ArrayList<>();
	ports.add(445);
	ports.add(443);

	SubnetDevices.fromLocalAddress().findDevices(new SubnetDevices.OnSubnetDeviceFound() {
							@Override
							public void onDeviceFound(Device device) {
                                // Stub: Found subnet device
                                
                            }

                            @Override
                            public void onFinished(ArrayList<Device> devicesFound) {
                                // your logic here for example:
                                for (Device device : devicesFound){
                                  ArrayList<Integer> openPorts = PortScan.onAddress(device.ip).setMethodTCP().setPorts(ports).doScan();       

                                }
                                

                            }
                                                    
	})
````

**Closed** 2023-07-08 21:00 UTC
Labels: Issue-Bug, Issue-Feature, Area-SMB
