### ISSUE TITLE
SD card as a Shared Path in FTP Server

### ISSUE THREAD

**Issue by Akhilesh-T** [TeamAmaze/AmazeFileManager#2364] opened 2021-03-15 18:23 UTC
**Is your feature request related to a problem? Please describe.**
SD card isn't available under **Shared Path** option. But there is also another issue with **Shared Path**.

If I
1. Click on **Shared Path**
2. Navigate to previous path by pressing the three dots (**...**)
3. **Choose This Folder**

Then, I'm unable to go to the original path again by clicking on **Shared Path** because the path I chose in step 3 becomes permanent. The only way to undo the path is by clearing the app data.

**Describe the solution you'd like**
I should be able to return to the original path.

**Describe alternatives you've considered**
**Material Files** app does offer the SD card path for FTP. I'd love this feature in Amaze File Manager.

**Comment by TranceLove** [comment] 2021-04-07 02:17
Duplicate of #1008, can be fixed by #2341.

**Closed by TranceLove** 2021-04-07 02:17 UTC
Labels: Issue-Bug
