### ISSUE TITLE
Change 'SD Card name' to just 'SD Card'

### ISSUE THREAD

**Issue by maverick74** [TeamAmaze/AmazeFileManager#1531] opened 2018-11-29 12:28 UTC
Instead of having a _weird_ 'SD Card name' it would be good to call it just '**SD Card**' (or, in case of multiple SD Cards, name them SD Card 1, SD Card 2, etc)).

This will enable users to easily identify their SD Cards's storage

**Comment by EmmanuelMess** [comment] 2018-11-30 18:46
Dupe of #1076.

**Closed** 2018-11-30 18:46 UTC
